### PR TITLE
Fix 131 Incorrect Mapping for @HeadMapping/@TraceMapping/@OptionsMapping

### PR DESCRIPTION
**Pull request by mikrethor**
Fix for the issue https://github.com/openapi-processor/openapi-processor-spring/issues/131.

I added unit tests but it seems integration tests are enough. Just tell me if you want me to remove them.

### CODE REVIEW

**Comment by hauner** [comment]
I usually prefer unit tests :-)  It is often simpler/faster to add an integration test but annoying to track down the issue if it fails and there are no unit tests.

it will go into the next release, it is not far way. :-)

Thanks!

**Comment by mikrethor** [comment]
Ok cool thanks for the reply.

**Comment by hauner** [comment]
released with 2022.5 :-)

**Comment by mikrethor** [comment]
Great thanks.

**Pull request merged**
